language: go
go:
  - "1.12.x"

cache:
  directories:
    - $HOME/.ccache

env:
  global:
  - DOCKER_IMG_VERSION=0.2
  - PACKAGE_NAME=docker-runu
  - RELEASE_VERSION=0.2
  - BINTRAY_REPO_NAME=debian
  - BINTRAY_ORG=ukontainer
  - BINTRAY_LICENSE=Apache-2.0
  - GO111MODULE=on

matrix:
  include:
    - os: linux
      cache:
        directories:
          - $HOME/.cache/go-build
      sudo: required
      env:
        - ARCH=amd64
        - DEB_ARCH=amd64
      before_install:
        - sudo apt-get install jq
    - os: linux
      cache:
        directories:
          - $HOME/.cache/go-build
      arch: arm64
      sudo: required
      env:
        - ARCH=arm
        - CC=arm-linux-gnueabihf-gcc
        - DEB_ARCH=armhf
        - RUNU_PATH="linux_arm/"
        - DOCKER_RUN_ARGS_ARCH="--platform=linux/arm"
      before_install:
        - sudo dpkg --add-architecture armhf
        - sudo apt-get update && sudo apt-get install jq libc6:armhf crossbuild-essential-armhf
        - export CGO_ENABLED=1
        - export GOARCH=arm
        - export PATH=$GOPATH/bin/linux_arm:$PATH
    - os: osx
      osx_image: xcode10.1
      cache:
        directories:
          - $HOME/Library/Caches/go-build
      env:
        - ARCH=amd64
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install jq
        - HOMEBREW_NO_AUTO_UPDATE=1 brew cask info tuntap
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ukontainer/lkl/dockerd-darwin
        - mkdir -p ~/.local/bin
        - export PATH=/usr/local/opt/ccache/libexec:$HOME/.local/bin:$PATH
        - ln -sf /usr/local/bin/gsha256sum ~/.local/bin/sha256sum
    - os: osx
      osx_image: xcode10.2
      cache:
        directories:
          - $HOME/Library/Caches/go-build
      env:
        - ARCH=amd64
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install jq
        - HOMEBREW_NO_AUTO_UPDATE=1 brew cask info tuntap
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ukontainer/lkl/dockerd-darwin
        - mkdir -p ~/.local/bin
        - export PATH=/usr/local/opt/ccache/libexec:$HOME/.local/bin:$PATH
        - ln -sf /usr/local/bin/gsha256sum ~/.local/bin/sha256sum

before_script:
  - export -f travis_nanoseconds
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish
  - export GO111MODULE=auto
  - go get -u github.com/gojp/goreportcard/cmd/goreportcard-cli
  - go get -u github.com/alecthomas/gometalinter
  - go get -u github.com/gordonklaus/ineffassign
  - go get -u github.com/fzipp/gocyclo
  - go get -u github.com/client9/misspell/cmd/misspell
  - go get -u golang.org/x/lint/golint
  # Export variables containing versions and filename
  - export BUILD_VERSION=$RELEASE_VERSION.$TRAVIS_BUILD_NUMBER
  - export BUILD_DATE=$(date "+%Y%m%d")
  - export PACKAGE_NAME_VERSION=$PACKAGE_NAME-$BUILD_VERSION-$DEB_ARCH.deb

script:
  - if [ $TRAVIS_ARCH = "amd64" ] && [ $TRAVIS_OS_NAME = "linux" ] ; then GO111MODULE=on goreportcard-cli -t 100.0 -v ; fi
  - bash -e test/standalone-test.sh
  - bash -e test/docker-oci-test.sh
  - bash -e test/containerd-ctr-test.sh

after_failure:
  - cat $HOME/dockerd.log
  - cat $HOME/containerd.log
  - cat $HOME/docker-manifest.log


## bintray package deploy
before_deploy:
  - bash -ex pkg/pre-deploy-deb.sh
  - bash -ex pkg/pre-deploy-test-deb.sh

deploy:
  # Upload debian packages to Bintray
  provider: bintray
  file: pkg/bintray-deb.json
  user: $BINTRAY_USER
  key: $BINTRAY_APIKEY
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME = linux
    branch: master

after_deploy:
  - bash -ex pkg/post-deploy-deb.sh
